BackendBundle\Entity\ImgBlog:
    type: entity
    table: img_blog
    indexes:
        fk_imgBlog_blog:
            columns:
                - id_blog
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        img:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        idBlog:
            targetEntity: Blog
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_blog:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
