BackendBundle\Entity\ImgDog:
    type: entity
    table: img_dog
    indexes:
        fk_imgDog_dog:
            columns:
                - id_dog
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        img:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        idDog:
            targetEntity: Dog
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_dog:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
