BackendBundle\Entity\ImgExotic:
    type: entity
    table: img_exotic
    indexes:
        fk_imgExotic_exotic:
            columns:
                - id_exotic
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        img:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        idExotic:
            targetEntity: Exotic
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_exotic:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
