BackendBundle\Entity\TypeExotic:
    type: entity
    table: type_exotic
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
