default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:Index"}
    methods: GET
    
default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login"}
    methods: POST
    
default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:Pruebas"}
    methods: POST